// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Rema1000.Models;

namespace Rema1000.Migrations
{
    [DbContext(typeof(RemaContext))]
    [Migration("20210524091728_initialsetup")]
    partial class initialsetup
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Rema1000.Models.Kategori", b =>
                {
                    b.Property<int>("KategoriId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Beskrivelse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Navn")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("KategoriId");

                    b.ToTable("Kategori");
                });

            modelBuilder.Entity("Rema1000.Models.Leverandør", b =>
                {
                    b.Property<int>("LeverandørId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Adresse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kontakperson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Navn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Postnr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefon")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LeverandørId");

                    b.ToTable("Leverandør");
                });

            modelBuilder.Entity("Rema1000.Models.Produkt", b =>
                {
                    b.Property<int>("ProduktId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Beskrivelse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Enhed")
                        .HasColumnType("real");

                    b.Property<int?>("KategoriId1")
                        .HasColumnType("int");

                    b.Property<int>("Lager")
                        .HasColumnType("int");

                    b.Property<int?>("LeverandørId1")
                        .HasColumnType("int");

                    b.Property<int>("Mængde")
                        .HasColumnType("int");

                    b.Property<string>("Navn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Pris")
                        .HasColumnType("real");

                    b.HasKey("ProduktId");

                    b.HasIndex("KategoriId1");

                    b.HasIndex("LeverandørId1");

                    b.ToTable("Produkt");
                });

            modelBuilder.Entity("Rema1000.Models.Produkt", b =>
                {
                    b.HasOne("Rema1000.Models.Kategori", "KategoriId")
                        .WithMany()
                        .HasForeignKey("KategoriId1");

                    b.HasOne("Rema1000.Models.Leverandør", "LeverandørId")
                        .WithMany()
                        .HasForeignKey("LeverandørId1");

                    b.Navigation("KategoriId");

                    b.Navigation("LeverandørId");
                });
#pragma warning restore 612, 618
        }
    }
}
